var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(p){b.reject(p)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(p){this.reject_(p);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var g=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(r){f(r)}}:
b}var d,f,g=new e(function(a,b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return g};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
d){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())c(g.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function g(b){return function(c){m[b]=c;t--;0==t&&a(m)}}var m=[],t=0;do m.push(void 0),t++,c(d.value).callWhenSettled_(g(m.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function g(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=b[c];if(g===a||Object.is(g,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
var text="null",playerData,leaderboard,promotedGameBar,gamma=0,downFallSpeed=1,score=0,player,levelManager,upSpeed=1.4,vectorY=-800,ads;function initGame(a,b){playerData=new PlayerData({soundVolume:20,isMusicEnabled:!0});playerData.readData();Time.init();leaderboard=new Leaderboard;promotedGameBar=new PromotedGameBar(a,b,4);ads=new Ads;gamma=0;player=new Player;levelManager=new LevelManager}function addScore(){score+=1}
function updateGame(){Time.refresh();player.move();upSpeed=0<=score&&50>score?1.4:50<=score&&90>score?1.6:90<=score&&120>score?1.8:120<=score&&150>score?2:2.3}function getShareText(){return"No one can stop you from going upward. \n"+FBInterface.playerName+": My best score is "+leaderboard.bestScore+". How about you?"}function initFBInterface(a){FBInterface.initFunctions(a)}function emptyFBInterface(){FBInterface.emptyFunctions()};(function(a,b){"object"===typeof exports&&"undefined"!==typeof module?b(exports):"function"===typeof define&&define.amd?define(["exports"],b):b(a.WHATWGFetch={})})(this,function(a){function b(a){"string"!==typeof a&&(a=String(a));if(/[^a-z0-9\-#$%&'*+.^_`|~]/i.test(a))throw new TypeError("Invalid character in header field name");return a.toLowerCase()}function c(a){"string"!==typeof a&&(a=String(a));return a}function d(a){var b={next:function(){var b=a.shift();return{done:void 0===b,value:b}}};k.iterable&&
(b[Symbol.iterator]=function(){return b});return b}function e(a){this.map={};a instanceof e?a.forEach(function(a,b){this.append(b,a)},this):Array.isArray(a)?a.forEach(function(a){this.append(a[0],a[1])},this):a&&Object.getOwnPropertyNames(a).forEach(function(b){this.append(b,a[b])},this)}function g(a){if(a.bodyUsed)return Promise.reject(new TypeError("Already read"));a.bodyUsed=!0}function f(a){return new Promise(function(b,c){a.onload=function(){b(a.result)};a.onerror=function(){c(a.error)}})}function h(a){var b=
new FileReader,c=f(b);b.readAsArrayBuffer(a);return c}function p(a){a=new Uint8Array(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=String.fromCharCode(a[c]);return b.join("")}function l(a){if(a.slice)return a.slice(0);var b=new Uint8Array(a.byteLength);b.set(new Uint8Array(a));return b.buffer}function u(){this.bodyUsed=!1;this._initBody=function(a){(this._bodyInit=a)?"string"===typeof a?this._bodyText=a:k.blob&&Blob.prototype.isPrototypeOf(a)?this._bodyBlob=a:k.formData&&FormData.prototype.isPrototypeOf(a)?
this._bodyFormData=a:k.searchParams&&URLSearchParams.prototype.isPrototypeOf(a)?this._bodyText=a.toString():k.arrayBuffer&&k.blob&&a&&DataView.prototype.isPrototypeOf(a)?(this._bodyArrayBuffer=l(a.buffer),this._bodyInit=new Blob([this._bodyArrayBuffer])):k.arrayBuffer&&(ArrayBuffer.prototype.isPrototypeOf(a)||z(a))?this._bodyArrayBuffer=l(a):this._bodyText=a=Object.prototype.toString.call(a):this._bodyText="";this.headers.get("content-type")||("string"===typeof a?this.headers.set("content-type","text/plain;charset=UTF-8"):
this._bodyBlob&&this._bodyBlob.type?this.headers.set("content-type",this._bodyBlob.type):k.searchParams&&URLSearchParams.prototype.isPrototypeOf(a)&&this.headers.set("content-type","application/x-www-form-urlencoded;charset=UTF-8"))};k.blob&&(this.blob=function(){var a=g(this);if(a)return a;if(this._bodyBlob)return Promise.resolve(this._bodyBlob);if(this._bodyArrayBuffer)return Promise.resolve(new Blob([this._bodyArrayBuffer]));if(this._bodyFormData)throw Error("could not read FormData body as blob");
return Promise.resolve(new Blob([this._bodyText]))},this.arrayBuffer=function(){return this._bodyArrayBuffer?g(this)||Promise.resolve(this._bodyArrayBuffer):this.blob().then(h)});this.text=function(){var a=g(this);if(a)return a;if(this._bodyBlob){a=this._bodyBlob;var b=new FileReader,c=f(b);b.readAsText(a);return c}if(this._bodyArrayBuffer)return Promise.resolve(p(this._bodyArrayBuffer));if(this._bodyFormData)throw Error("could not read FormData body as text");return Promise.resolve(this._bodyText)};
k.formData&&(this.formData=function(){return this.text().then(m)});this.json=function(){return this.text().then(JSON.parse)};return this}function n(a,b){b=b||{};var c=b.body;if(a instanceof n){if(a.bodyUsed)throw new TypeError("Already read");this.url=a.url;this.credentials=a.credentials;b.headers||(this.headers=new e(a.headers));this.method=a.method;this.mode=a.mode;this.signal=a.signal;c||null==a._bodyInit||(c=a._bodyInit,a.bodyUsed=!0)}else this.url=String(a);this.credentials=b.credentials||this.credentials||
"same-origin";if(b.headers||!this.headers)this.headers=new e(b.headers);a=b.method||this.method||"GET";var d=a.toUpperCase();this.method=-1<A.indexOf(d)?d:a;this.mode=b.mode||this.mode||null;this.signal=b.signal||this.signal;this.referrer=null;if(("GET"===this.method||"HEAD"===this.method)&&c)throw new TypeError("Body not allowed for GET or HEAD requests");this._initBody(c)}function m(a){var b=new FormData;a.trim().split("&").forEach(function(a){if(a){var c=a.split("=");a=c.shift().replace(/\+/g,
" ");c=c.join("=").replace(/\+/g," ");b.append(decodeURIComponent(a),decodeURIComponent(c))}});return b}function t(a){var b=new e;a.replace(/\r?\n[\t ]+/g," ").split(/\r?\n/).forEach(function(a){var c=a.split(":");if(a=c.shift().trim())c=c.join(":").trim(),b.append(a,c)});return b}function q(a,b){b||(b={});this.type="default";this.status=void 0===b.status?200:b.status;this.ok=200<=this.status&&300>this.status;this.statusText="statusText"in b?b.statusText:"OK";this.headers=new e(b.headers);this.url=
b.url||"";this._initBody(a)}function r(b,c){return new Promise(function(d,e){function m(){f.abort()}var g=new n(b,c);if(g.signal&&g.signal.aborted)return e(new a.DOMException("Aborted","AbortError"));var f=new XMLHttpRequest;f.onload=function(){var a={status:f.status,statusText:f.statusText,headers:t(f.getAllResponseHeaders()||"")};a.url="responseURL"in f?f.responseURL:a.headers.get("X-Request-URL");d(new q("response"in f?f.response:f.responseText,a))};f.onerror=function(){e(new TypeError("Network request failed"))};
f.ontimeout=function(){e(new TypeError("Network request failed"))};f.onabort=function(){e(new a.DOMException("Aborted","AbortError"))};f.open(g.method,g.url,!0);"include"===g.credentials?f.withCredentials=!0:"omit"===g.credentials&&(f.withCredentials=!1);"responseType"in f&&k.blob&&(f.responseType="blob");g.headers.forEach(function(a,b){f.setRequestHeader(b,a)});g.signal&&(g.signal.addEventListener("abort",m),f.onreadystatechange=function(){4===f.readyState&&g.signal.removeEventListener("abort",m)});
f.send("undefined"===typeof g._bodyInit?null:g._bodyInit)})}var w="Symbol"in self&&"iterator"in Symbol,v;if(v="FileReader"in self&&"Blob"in self)try{new Blob,v=!0}catch(y){v=!1}var k={searchParams:"URLSearchParams"in self,iterable:w,blob:v,formData:"FormData"in self,arrayBuffer:"ArrayBuffer"in self};if(k.arrayBuffer)var B="[object Int8Array];[object Uint8Array];[object Uint8ClampedArray];[object Int16Array];[object Uint16Array];[object Int32Array];[object Uint32Array];[object Float32Array];[object Float64Array]".split(";"),
z=ArrayBuffer.isView||function(a){return a&&-1<B.indexOf(Object.prototype.toString.call(a))};e.prototype.append=function(a,d){a=b(a);d=c(d);var e=this.map[a];this.map[a]=e?e+", "+d:d};e.prototype["delete"]=function(a){delete this.map[b(a)]};e.prototype.get=function(a){a=b(a);return this.has(a)?this.map[a]:null};e.prototype.has=function(a){return this.map.hasOwnProperty(b(a))};e.prototype.set=function(a,d){this.map[b(a)]=c(d)};e.prototype.forEach=function(a,b){for(var c in this.map)this.map.hasOwnProperty(c)&&
a.call(b,this.map[c],c,this)};e.prototype.keys=function(){var a=[];this.forEach(function(b,c){a.push(c)});return d(a)};e.prototype.values=function(){var a=[];this.forEach(function(b){a.push(b)});return d(a)};e.prototype.entries=function(){var a=[];this.forEach(function(b,c){a.push([c,b])});return d(a)};k.iterable&&(e.prototype[Symbol.iterator]=e.prototype.entries);var A="DELETE GET HEAD OPTIONS POST PUT".split(" ");n.prototype.clone=function(){return new n(this,{body:this._bodyInit})};u.call(n.prototype);
u.call(q.prototype);q.prototype.clone=function(){return new q(this._bodyInit,{status:this.status,statusText:this.statusText,headers:new e(this.headers),url:this.url})};q.error=function(){var a=new q(null,{status:0,statusText:""});a.type="error";return a};var x=[301,302,303,307,308];q.redirect=function(a,b){if(-1===x.indexOf(b))throw new RangeError("Invalid status code");return new q(null,{status:b,headers:{location:a}})};a.DOMException=self.DOMException;try{new a.DOMException}catch(y){a.DOMException=
function(a,b){this.message=a;this.name=b;this.stack=Error(a).stack},a.DOMException.prototype=Object.create(Error.prototype),a.DOMException.prototype.constructor=a.DOMException}r.polyfill=!0;self.fetch||(self.fetch=r,self.Headers=e,self.Request=n,self.Response=q);a.Headers=e;a.Request=n;a.Response=q;a.fetch=r;Object.defineProperty(a,"__esModule",{value:!0})});(function(a,b){"object"===typeof exports&&"undefined"!==typeof module?b():"function"===typeof define&&define.amd?define(b):b()})(this,function(){function a(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})}function b(){}function c(a,b){return function(){a.apply(b,arguments)}}function d(a){if(!(this instanceof d))throw new TypeError("Promises must be constructed via new");
if("function"!==typeof a)throw new TypeError("not a function");this._state=0;this._handled=!1;this._value=void 0;this._deferreds=[];l(a,this)}function e(a,b){for(;3===a._state;)a=a._value;0===a._state?a._deferreds.push(b):(a._handled=!0,d._immediateFn(function(){var c=1===a._state?b.onFulfilled:b.onRejected;if(null===c)(1===a._state?g:f)(b.promise,a._value);else{try{var d=c(a._value)}catch(w){f(b.promise,w);return}g(b.promise,d)}}))}function g(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");
if(b&&("object"===typeof b||"function"===typeof b)){var e=b.then;if(b instanceof d){a._state=3;a._value=b;h(a);return}if("function"===typeof e){l(c(e,b),a);return}}a._state=1;a._value=b;h(a)}catch(r){f(a,r)}}function f(a,b){a._state=2;a._value=b;h(a)}function h(a){2===a._state&&0===a._deferreds.length&&d._immediateFn(function(){a._handled||d._unhandledRejectionFn(a._value)});for(var b=0,c=a._deferreds.length;b<c;b++)e(a,a._deferreds[b]);a._deferreds=null}function p(a,b,c){this.onFulfilled="function"===
typeof a?a:null;this.onRejected="function"===typeof b?b:null;this.promise=c}function l(a,b){var c=!1;try{a(function(a){c||(c=!0,g(b,a))},function(a){c||(c=!0,f(b,a))})}catch(r){c||(c=!0,f(b,r))}}var u=setTimeout;d.prototype["catch"]=function(a){return this.then(null,a)};d.prototype.then=function(a,c){var d=new this.constructor(b);e(this,new p(a,c,d));return d};d.prototype["finally"]=a;d.all=function(a){return new d(function(b,c){function d(a,f){try{if(f&&("object"===typeof f||"function"===typeof f)){var m=
f.then;if("function"===typeof m){m.call(f,function(b){d(a,b)},c);return}}e[a]=f;0===--g&&b(e)}catch(x){c(x)}}if(!a||"undefined"===typeof a.length)throw new TypeError("Promise.all accepts an array");var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var g=e.length,f=0;f<e.length;f++)d(f,e[f])})};d.resolve=function(a){return a&&"object"===typeof a&&a.constructor===d?a:new d(function(b){b(a)})};d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,
c){for(var d=0,e=a.length;d<e;d++)a[d].then(b,c)})};d._immediateFn="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){u(a,0)};d._unhandledRejectionFn=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};var n=function(){if("undefined"!==typeof self)return self;if("undefined"!==typeof window)return window;if("undefined"!==typeof global)return global;throw Error("unable to locate global object");}();"Promise"in n?n.Promise.prototype["finally"]||
(n.Promise.prototype["finally"]=a):n.Promise=d});var Time=function(){};Time.init=function(){this.lastTime=window.performance.now()};Time.refresh=function(){this.now=window.performance.now();this._deltaMiliseconds=this.now-this.lastTime;this.lastTime=this.now};$jscomp.global.Object.defineProperties(Time,{deltaMiliseconds:{configurable:!0,enumerable:!0,get:function(){return this._deltaMiliseconds}},deltaSeconds:{configurable:!0,enumerable:!0,get:function(){return this._deltaMiliseconds/1E3}},time:{configurable:!0,enumerable:!0,get:function(){return window.performance.now()}}});var Vector2=function(){function a(a,c){this.x=a;this.y=c}a.prototype.toString=function(){return"{X: "+this.x+" Y:"+this.y+"}"};a.prototype.getClassName=function(){return"Vector2"};a.prototype.getHashCode=function(){var a=this.x||0;return a=397*a^(this.y||0)};a.prototype.toArray=function(a,c){void 0===c&&(c=0);a[c]=this.x;a[c+1]=this.y;return this};a.prototype.asArray=function(){var a=[];this.toArray(a,0);return a};a.prototype.copyFrom=function(a){this.x=a.x;this.y=a.y;return this};a.prototype.copyFromFloats=
function(a,c){this.x=a;this.y=c;return this};a.prototype.set=function(a,c){return this.copyFromFloats(a,c)};a.prototype.add=function(b){return new a(this.x+b.x,this.y+b.y)};a.prototype.addToRef=function(a,c){c.x=this.x+a.x;c.y=this.y+a.y;return this};a.prototype.addInPlace=function(a){this.x+=a.x;this.y+=a.y;return this};a.prototype.addVector3=function(b){return new a(this.x+b.x,this.y+b.y)};a.prototype.subtract=function(b){return new a(this.x-b.x,this.y-b.y)};a.prototype.subtractToRef=function(a,
c){c.x=this.x-a.x;c.y=this.y-a.y;return this};a.prototype.subtractInPlace=function(a){this.x-=a.x;this.y-=a.y;return this};a.prototype.multiplyInPlace=function(a){this.x*=a.x;this.y*=a.y;return this};a.prototype.multiply=function(b){return new a(this.x*b.x,this.y*b.y)};a.prototype.multiplyToRef=function(a,c){c.x=this.x*a.x;c.y=this.y*a.y;return this};a.prototype.multiplyByFloats=function(b,c){return new a(this.x*b,this.y*c)};a.prototype.divide=function(b){return new a(this.x/b.x,this.y/b.y)};a.prototype.divideToRef=
function(a,c){c.x=this.x/a.x;c.y=this.y/a.y;return this};a.prototype.divideInPlace=function(a){return this.divideToRef(a,this)};a.prototype.negate=function(){return new a(-this.x,-this.y)};a.prototype.scaleInPlace=function(a){this.x*=a;this.y*=a;return this};a.prototype.scale=function(b){var c=new a(0,0);this.scaleToRef(b,c);return c};a.prototype.scaleToRef=function(a,c){c.x=this.x*a;c.y=this.y*a;return this};a.prototype.scaleAndAddToRef=function(a,c){c.x+=this.x*a;c.y+=this.y*a;return this};a.prototype.equals=
function(a){return a&&this.x===a.x&&this.y===a.y};a.prototype.equalsWithEpsilon=function(a,c){void 0===c&&(c=BABYLON.Epsilon);return a&&BABYLON.Scalar.WithinEpsilon(this.x,a.x,c)&&BABYLON.Scalar.WithinEpsilon(this.y,a.y,c)};a.prototype.length=function(){return Math.sqrt(this.x*this.x+this.y*this.y)};a.prototype.lengthSquared=function(){return this.x*this.x+this.y*this.y};a.prototype.normalize=function(){var a=this.length();if(0===a)return this;a=1/a;this.x*=a;this.y*=a;return this};a.prototype.clone=
function(){return new a(this.x,this.y)};a.Zero=function(){return new a(0,0)};a.One=function(){return new a(1,1)};a.FromArray=function(b,c){void 0===c&&(c=0);return new a(b[c],b[c+1])};a.FromArrayToRef=function(a,c,d){d.x=a[c];d.y=a[c+1]};a.CatmullRom=function(b,c,d,e,g){var f=g*g,h=g*f;return new a(.5*(2*c.x+(-b.x+d.x)*g+(2*b.x-5*c.x+4*d.x-e.x)*f+(-b.x+3*c.x-3*d.x+e.x)*h),.5*(2*c.y+(-b.y+d.y)*g+(2*b.y-5*c.y+4*d.y-e.y)*f+(-b.y+3*c.y-3*d.y+e.y)*h))};a.Clamp=function(b,c,d){var e=b.x;e=e>d.x?d.x:e;e=
e<c.x?c.x:e;b=b.y;b=b>d.y?d.y:b;b=b<c.y?c.y:b;return new a(e,b)};a.Hermite=function(b,c,d,e,g){var f=g*g,h=g*f,p=2*h-3*f+1,l=-2*h+3*f;g=h-2*f+g;f=h-f;return new a(b.x*p+d.x*l+c.x*g+e.x*f,b.y*p+d.y*l+c.y*g+e.y*f)};a.Lerp=function(b,c,d){return new a(b.x+(c.x-b.x)*d,b.y+(c.y-b.y)*d)};a.Dot=function(a,c){return a.x*c.x+a.y*c.y};a.Normalize=function(a){a=a.clone();a.normalize();return a};a.Minimize=function(b,c){return new a(b.x<c.x?b.x:c.x,b.y<c.y?b.y:c.y)};a.Maximize=function(b,c){return new a(b.x>
c.x?b.x:c.x,b.y>c.y?b.y:c.y)};a.Transform=function(b,c){var d=a.Zero();a.TransformToRef(b,c,d);return d};a.TransformToRef=function(a,c,d){var b=a.x*c.m[1]+a.y*c.m[5]+c.m[13];d.x=a.x*c.m[0]+a.y*c.m[4]+c.m[12];d.y=b};a.PointInTriangle=function(a,c,d,e){var b=.5*(-d.y*e.x+c.y*(-d.x+e.x)+c.x*(d.y-e.y)+d.x*e.y),f=0>b?-1:1;e=(c.y*e.x-c.x*e.y+(e.y-c.y)*a.x+(c.x-e.x)*a.y)*f;a=(c.x*d.y-c.y*d.x+(c.y-d.y)*a.x+(d.x-c.x)*a.y)*f;return 0<e&&0<a&&e+a<2*b*f};a.Distance=function(b,c){return Math.sqrt(a.DistanceSquared(b,
c))};a.DistanceSquared=function(a,c){var b=a.x-c.x;a=a.y-c.y;return b*b+a*a};a.Center=function(a,c){a=a.add(c);a.scaleInPlace(.5);return a};a.DistanceOfPointFromSegment=function(b,c,d){var e=a.DistanceSquared(c,d);if(0===e)return a.Distance(b,c);d=d.subtract(c);e=Math.max(0,Math.min(1,a.Dot(b.subtract(c),d)/e));c=c.add(d.multiplyByFloats(e,e));return a.Distance(b,c)};return a}();var Angle=function(){function a(a){this._radians=a;0>this._radians&&(this._radians+=2*Math.PI)}a.prototype.degrees=function(){return 180*this._radians/Math.PI};a.prototype.radians=function(){return this._radians};a.BetweenTwoPoints=function(b,c){b=c.subtract(b);return new a(Math.atan2(b.y,b.x))};a.BetweenVectors=function(a,c){var b=Vector2.Zero();a=this.BetweenTwoPoints(b,a).radians();c=this.BetweenTwoPoints(b,c).radians();return this.FromRadians(c-a)};a.FromRadians=function(b){return new a(b)};a.FromDegrees=
function(b){return new a(b*Math.PI/180)};return a}();var BIPlatform=function(){};BIPlatform.init=function(a,b,c){this.gameName=a;this.numOfRequestedGames=b;this.isPlayerInfoLoaded=!1;this.url=(c?"https://test.bananas.games":"https://bananas.games")+"/GamePromotion";this.requestHeader=new Headers({Accept:"application/json","Content-Type":"application/json","Access-Control-Allow-Headers":"X-Requested-With","Access-Control-Request-Method":"POST"})};
BIPlatform.fetchPromotedGamesAsync=function(){var a=this,b,c,d,e,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){switch(f.nextAddress){case 1:if(a.isPlayerInfoLoaded){f.jumpTo(2);break}a.isPlayerInfoLoaded=!0;return f.yield(FBInterface.getSignedPlayerInfoAsync(),3);case 3:b=f.yieldResult,void 0!=b&&(c=b.getPlayerID(),d=b.getSignature()),a.requestData=JSON.stringify({gameName:a.gameName,numOfRequestedGames:a.numOfRequestedGames,playerID:c,signature:d});case 2:return e=new Request(a.url,
{method:"POST",body:a.requestData,headers:a.requestHeader}),f.yield(fetch(e),4);case 4:return g=f.yieldResult,f.return(new Promise(function(a,b){return g.ok?a(g.json()):b(Error(g))}))}})};var PromotedGameBar=function(a,b,c){this.images=Array(c);this.gameID=Array(c);this.isLoaded=this.isEnabled=!1;BIPlatform.init(a,c,b)};
PromotedGameBar.prototype.fetch=function(){var a=this;BIPlatform.fetchPromotedGamesAsync().then(function(b){if(b.length<BIPlatform.numOfRequestedGames)throw"Expected to promoted "+BIPlatform.numOfRequestedGames+"games, but only "+b.length+"games supplied!";a.retrieveData(b)}).catch(function(a){console.log("some error happened when fetching promoted games.");console.log(a)})};
PromotedGameBar.prototype.retrieveData=function(a){for(var b=0;b<a.length;++b)this.images[b]="data:image/png;base64,"+a[b].imgData,this.gameID[b]=a[b].gameID;this.isLoaded=this.isEnabled=!0};PromotedGameBar.prototype.onClickButton=function(a){FBInterface.switchGameAsync(this.gameID[a])};var PlayerData=function(a){this.data=this.initialData=a;this.propName="str";this.props=[this.propName];this.isReady=!1;this.delayTime=800;this.updateFunc=this.update.bind(this);this.update=function(){}};PlayerData.prototype.isValid=function(a){return a.hasOwnProperty(this.propName)};
PlayerData.prototype.readData=function(){var a=this;FBInterface.readData(this.props,function(b){console.log("data is loaded");a.data=a.initialData;if(a.isValid(b)){b=JSON.parse(b[a.propName]);for(var c in a.data)b.hasOwnProperty(c)&&(a.data[c]=b[c])}a.isReady=!0})};PlayerData.prototype.saveData=function(){FBInterface.saveData({str:JSON.stringify(this.data)})};PlayerData.prototype.delaySaveData=function(){this.update=this.updateFunc;this.lastTime=Time.time};
PlayerData.prototype.update=function(){Time.time-this.lastTime>this.delayTime&&(this.saveData(),this.update=function(){})};var FBInterface=function(){};
FBInterface.initFunctions=function(a){this.isAdsDisabled=this.isLeaderboardAvailable=!0;this.isTesting=a;this.interAds=this.videoAds=null;this.helpList=[];this.sharePayload={intent:"CHALLENGE",image:null,text:null,data:{mydata:""}};this.updatePayload={action:"CUSTOM",cta:"HELP THEM!!",template:"Get Help",image:null,text:null,data:{mydata:""},strategy:"IMMEDIATE_CLEAR",notification:"NO_PUSH"};this.requestTime=1;this.maxRequestTime=3;this.playerName=FBInstant.player.getName();this.playerPhoto=FBInstant.player.getPhoto();
this.setLoadingProgress=FBInstant.setLoadingProgress.bind(FBInstant);this.switchGameAsync=FBInstant.switchGameAsync.bind(FBInstant);this.getSignedPlayerInfoAsync=FBInstant.player.getSignedPlayerInfoAsync.bind(FBInstant);this.shareAsync=FBInstant.shareAsync.bind(FBInstant)};
FBInterface.emptyFunctions=function(){this.isLeaderboardAvailable=!1;this.playerName="--";this.playerPhoto=0;this.readData=function(){};this.saveData=function(){};this.setLeaderboard=function(){};this.switchGameAsync=function(){};this.getSignedPlayerInfoAsync=function(){};this.shareAsync=function(){};this.playFriends=function(){};this.showAds=function(){return!1}};
FBInterface.setLeaderboard=function(a,b){var c=this,d=!1;FBInstant.getLeaderboardAsync(a).then(function(a){d=!0;c.requestTime=1;b(a)}).catch(function(e){console.error(e);++c.requestTime>c.maxRequestTime||d?(d&&(c.isLeaderboardAvailable=!1),c.requestTime=1,console.error("Request time-out, Failed to load leaderboard")):c.setLeaderboard(a,b)})};FBInterface.readData=function(a,b){FBInstant.player.getDataAsync(a).then(b)};FBInterface.saveData=function(a){FBInstant.player.setDataAsync(a).then(function(){console.log("data is set")})};
FBInterface.playFriends=function(a,b,c,d){var e=this;this.updatePayload.text=a;this.updatePayload.image=b;void 0==c&&(c=function(){});void 0==d&&(d=function(){});FBInstant.context.chooseAsync().then(function(){c();FBInstant.updateAsync(e.updatePayload)}).catch(function(a){"SAME_CONTEXT"==a.code&&d()})};
FBInterface.playFriends_2=function(a,b,c,d){var e=this;this.updatePayload.text=a;this.updatePayload.image=b;void 0==c&&(c=function(){});void 0==d&&(d=function(){});FBInstant.context.chooseAsync({filters:["NEW_CONTEXT_ONLY","NEW_PLAYERS_ONLY"],minSize:3}).then(function(){e.getContexPlayer(function(a){var b=a.getName();e.helpList.includes(b)?d(a):(e.helpList.push(b),c(a),FBInstant.updateAsync(e.updatePayload))})}).catch(function(a){"SAME_CONTEXT"==a.code&&e.getContexPlayer(d)})};
FBInterface.getContexPlayer=function(a){var b=this;FBInstant.context.getPlayersAsync().then(function(c){c[0].getName()!=b.playerName?a(c[0]):a(c[1])})};FBInterface.showAds=function(a,b,c){a=a?this.videoAds:this.interAds;if(null==a)return this.isLeaderboardAvailable&&(this.videoAds=new FBAdvertisement(this.isTesting,0),this.interAds=new FBAdvertisement(this.isTesting,1)),!1;a.showAds(b,c);return!0};var FBAdvertisement=function(a,b){var c=["1631063763695702_1640480716087340","1631063763695702_1640480632754015"],d=["1834900569898948_2055533741168962","1834900569898948_2055531067835896"],e=[FBInstant.getRewardedVideoAsync,FBInstant.getInterstitialAdAsync];this.id=a?d[b]:c[b];this.getAds=e[b];this.data=null;this.error="NONE";this.reloadTime=0;this.preloadAds()};
FBAdvertisement.prototype.preloadAds=function(){var a=this;this.getAds(this.id).then(function(b){a.data=b;return b.loadAsync()}).then(function(){a.error="NONE";a.reloadTime=0;FBInterface.isAdsDisabled=!1}).catch(function(b){a.error=b.code;"ADS_NO_FILL"==a.error&&3>++a.reloadTime?setTimeout(a.preloadAds.bind(a),5E3):a.reloadTime=0})};
FBAdvertisement.prototype.showAds=function(a,b){var c=this,d=this.error;"NONE"!=d?(b(d),"ADS_NO_FILL"!=d&&"NETWORK_FAILURE"!=d&&"ADS_TOO_MANY_INSTANCES"!=d||this.preloadAds()):(this.data.showAsync().then(function(){a()}).catch(function(a){b(a.code);"ADS_NOT_LOADED"==a.code&&(c.error=a.code)}),"ADS_NOT_LOADED"!=this.error?this.preloadAds():this.error="NONE")};var Leaderboard=function(){this.requestNumb=5;this.leaderboardName="HighScore";this.isLoaded=[!1,!1];this.leaderboards=Array(2);this.curIndex=Array(2);this.curPlayer=Array(2);this.bestScore=-1;this.rank="--";this.isScoreLoaded=!1;this.fakePlayer=new function(){var a=this;this.player=new function(){this.getPhoto=function(){return 0};this.getName=function(){return"--"}};this.getScore=function(){return"--"};this.getPlayer=function(){return a.player}}};
Leaderboard.prototype.updateScore=function(a){a>this.bestScore&&(this.bestScore=a,FBInterface.setLeaderboard(this.leaderboardName,this.saveScore.bind(this)))};Leaderboard.prototype.isLoaded_local=function(){return this.isLoaded[0]};Leaderboard.prototype.init_local=function(){this.curIndex[0]=-1};Leaderboard.prototype.nextPlayer_local=function(){var a=++this.curIndex[0],b=this.leaderboards[0];this.curPlayer[0]=a<b.length?b[a]:this.fakePlayer};Leaderboard.prototype.getPhoto_local=function(){return this.curPlayer[0].getPlayer().getPhoto()};
Leaderboard.prototype.getName_local=function(){return this.curPlayer[0].getPlayer().getName()};Leaderboard.prototype.getScore_local=function(){return this.curPlayer[0].getScore().toString()};Leaderboard.prototype.finishLoading_local=function(){this.isLoaded[0]=!1};Leaderboard.prototype.isLoaded_global=function(){return this.isLoaded[1]};Leaderboard.prototype.init_global=function(){this.curIndex[1]=-1};
Leaderboard.prototype.nextPlayer_global=function(){var a=++this.curIndex[1],b=this.leaderboards[1];this.curPlayer[1]=a<b.length?b[a]:this.fakePlayer};Leaderboard.prototype.getPhoto_global=function(){return this.curPlayer[1].getPlayer().getPhoto()};Leaderboard.prototype.getName_global=function(){return this.curPlayer[1].getPlayer().getName()};Leaderboard.prototype.getScore_global=function(){return this.curPlayer[1].getScore().toString()};
Leaderboard.prototype.finishLoading_global=function(){this.isLoaded[1]=!1};Leaderboard.prototype.onleaderboardLoaded=function(a,b){this.leaderboards[b]=a;this.curIndex[b]=-1;this.isLoaded[b]=!0};
Leaderboard.prototype.readScore=function(a){var b=this;a.getPlayerEntryAsync().then(function(a){null!=a&&(b.bestScore=a.getScore(),b.rank=a.getRank());b.isScoreLoaded=!0});a.getEntriesAsync(this.requestNumb).then(function(a){return b.onleaderboardLoaded(a,1)});a.getConnectedPlayerEntriesAsync(this.requestNumb).then(function(a){return b.onleaderboardLoaded(a,0)})};Leaderboard.prototype.saveScore=function(a){var b=this;a.setScoreAsync(this.bestScore).then(function(){console.log("Score Saved");b.readScore(a)}).catch(function(a){return console.error(a)})};var Ads=function(){this.maxWaitTime=20;this.interCounter=0;this.reset()};Ads.prototype.reset=function(){this.isError=this.isWatched=!1};Ads.prototype.onWatched=function(){this.isWatched=!0};Ads.prototype.onError=function(a){this.isError=!0;this.errorMessage=a};
Ads.prototype.showAds=function(a){if(a){if(FBInterface.showAds(a,this.onWatched.bind(this),this.onError.bind(this)))return!0;this.isError=!0;this.errorMessage="FAIL TO LOAD ADS";return!1}return Time.time>this.interCounter&&FBInterface.showAds(a,this.onWatched.bind(this),this.onError.bind(this))?(this.interCounter=Time.time+1E3*this.maxWaitTime,this.maxWaitTime=40,!0):!1};var LevelManager=function(){this.currentIndex=this.generalIndex=0;this.currentSeq=[];this.pageDis=this.count=this.baseY=0;this.cacheNumber=40};LevelManager.prototype.getTemplate=function(a,b,c){this.currentSeq=levels[a][b][c][Math.floor(levels[a][b][c].length*Math.random())];console.log(this.currentSeq.length)};LevelManager.prototype.clear=function(){this.index=[0,0,0];this.generalIndex=this.currentIndex=0;this.currentSeq=[];this.baseY=0;this.baseX=100;this.pageDis=this.count=0};
LevelManager.prototype.subBaseY=function(a){this.baseY-=a};LevelManager.prototype.addBaseY=function(a){this.baseY+=a};LevelManager.prototype.extendBase=function(a){var b=this.currentSeq.length;switch(a){case "left":console.log(a);break;case "right":console.log(a);break;case "down":this.baseY+=this.space+this.currentSeq[b-1][2];console.log(a);break;case "up":console.log(this.space),this.baseY-=854,console.log(a)}};
LevelManager.prototype.changeBase=function(a,b){switch(a){case "left":console.log(a);break;case "right":console.log(a);break;case "down":this.baseY-=b;console.log(a);break;case "up":this.baseY+=b}};LevelManager.prototype.extendDownBaseY=function(){this.baseY+=this.space+this.currentSeq[this.currentSeq.length-1][2]};LevelManager.prototype.extendUpBaseY=function(){this.baseY-=this.space+this.currentSeq[this.currentSeq.length-1][2]};
LevelManager.prototype.extendLeftBaseX=function(){this.baseX+=this.space+this.currentSeq[this.currentSeq.length-1][1]};LevelManager.prototype.extendRightBaseX=function(){this.baseX-=this.space+this.currentSeq[this.currentSeq.length-1][1]};LevelManager.prototype.init=function(){this.currentIndex=0;var a=0!=this.count&&0==this.count%sequence.length?1:this.count%sequence.length;this.space=sequence[a][0];this.getTemplate(sequence[a][1],sequence[a][2],sequence[a][3]);this.count++};
LevelManager.prototype.draw=function(){this.element=this.currentSeq[this.currentIndex];this.currentIndex+=1};LevelManager.prototype.pick=function(){this.generalIndex++;this.generalIndex>=this.cacheNumber&&(this.generalIndex=0)};LevelManager.prototype.getID=function(){return this.element[0]};LevelManager.prototype.getPosX=function(){return this.element[1]};LevelManager.prototype.getPosY=function(){return this.baseY+this.space+this.element[2]};LevelManager.prototype.getWidth=function(){return this.element[3]};
LevelManager.prototype.getHeight=function(){return this.element[4]};LevelManager.prototype.getAngle=function(){return this.element[5]};var Player=function(){};Player.prototype.move=function(){this.X+=this.speedX};Player.prototype.antiMove=function(a){this.X-=a*this.speedX};Player.prototype.init=function(){this.speedX=0;this.X=230;this.Y=380};Player.prototype.setSpeed=function(a){this.speedX=a};Player.prototype.setGamma=function(a){gamma=a};Player.prototype.setX=function(a){this.X=a};var levels=[[[[[[3,221.38,52.98,179.4,44,0],[1,233.09,182.77,126.75,69,0],[0,344.19,315.03,186.23,39,0],[3,78.8,423.58,179.4,44,0],[1,326.71,477.45,126.75,69,0],[3,328.84,644.47,179.4,44,0],[0,99.11,758.75,186.23,39,0]]],[[[1,257.55,46.6,126.75,69,0],[3,263.59,270.26,179.4,44,0]]],[[[0,366.06,94.47,186.23,39,0],[1,118.8,225.55,126.75,69,0],[3,133.5,373.93,179.4,44,0],[0,341.36,485.95,186.23,39,0],[1,365.82,627.65,126.75,69,0],[3,80.77,634.38,179.4,44,0],[0,104.56,788.89,186.23,39,0]]]],[[[[1,125.13,
82.63,126.75,69,0],[3,363.94,83.83,179.4,44,0],[0,378.59,204.96,186.23,39,0],[3,279.48,350.59,179.4,44,0],[0,97.43,478.03,186.23,39,0],[1,168.22,623.67,126.75,69,0],[0,233.97,764.25,186.23,39,0]]],[[[3,243.07,76.51,179.4,44,0],[2,97.43,217.09,175.5,45,0],[3,124.57,357.23,179.4,44,0],[1,350.27,358.69,126.75,69,0],[0,99.45,492.19,186.23,39,0],[3,220.82,656.03,179.4,44,0],[2,379.6,798.63,175.5,45,0]]],[[[2,389.72,43.14,175.5,45,0],[0,99.45,174.61,186.23,39,0],[3,329.03,320.25,179.4,44,0],[2,96.42,452.74,
175.5,45,0],[1,235.99,619.62,126.75,69,0],[0,376.57,772.34,186.23,39,0]]]],[[[[2,121.38,31.7,175.5,45,0],[3,295.85,157.23,179.4,44,0],[3,361.81,262.55,179.4,44,0],[2,104.36,391.28,175.5,45,0],[0,361.81,532.77,186.23,39,0],[3,111.81,676.38,179.4,44,0],[1,352.23,740.21,126.75,69,0]]],[[[0,368.19,55.11,186.23,39,0],[2,121.38,202.98,175.5,45,0],[1,322.45,343.4,126.75,69,0],[3,127.77,509.36,179.4,44,0],[2,367.13,666.81,175.5,45,0],[0,102.23,787.02,186.23,39,0]]],[[[3,240.03,43.14,179.4,44,0],[0,103.5,
168.55,186.23,39,0],[2,388.7,294.97,175.5,45,0],[1,253.18,438.58,126.75,69,0],[2,99.45,606.47,175.5,45,0],[0,364.43,755.15,186.23,39,0]]]],[[[[1,246.1,55.27,126.75,69,0],[1,241.04,272.72,126.75,69,0],[0,126.76,411.28,186.23,39,0],[3,224.86,544.78,179.4,44,0],[3,379.6,651.98,179.4,44,0],[3,83.27,651.98,179.4,44,0],[1,242.05,777.4,126.75,69,0]]],[[[3,146.98,37.07,179.4,44,0],[3,137.88,216.08,179.4,44,0],[1,141.93,358.69,126.75,69,0],[0,357.35,482.07,186.23,39,0],[1,239.02,628.72,126.75,69,0],[3,229.92,
765.26,179.4,44,0]]],[[[0,100.46,48.19,186.23,39,0],[3,256.21,167.53,179.4,44,0],[3,254.19,307.1,179.4,44,0],[3,250.15,441.62,179.4,44,0],[2,344.2,612.54,175.5,45,0],[1,97.43,747.05,126.75,69,0],[1,386.68,755.15,126.75,69,0]]]],[[[[2,242.05,46.17,175.5,45,0],[1,257.23,201.92,126.75,69,0],[0,146.98,352.62,186.23,39,0],[0,310.83,500.28,186.23,39,0],[3,107.54,640.86,179.4,44,0],[3,359.37,752.11,179.4,44,0]]],[[[2,93.38,48.19,175.5,45,0],[1,223.85,271.71,126.75,69,0],[0,106.53,402.17,186.23,39,0],[3,
224.86,551.86,179.4,44,0],[2,379.6,771.33,175.5,45,0]]],[[[3,229.92,61.34,179.4,44,0],[3,232.95,192.82,179.4,44,0],[0,361.4,346.55,186.23,39,0],[0,108.55,476.01,186.23,39,0],[1,399.83,622.65,126.75,69,0],[1,72.14,629.73,126.75,69,0],[2,240.03,786.5,175.5,45,0]]]],[[[[3,229.92,41.11,179.4,44,0],[2,377.57,170.57,175.5,45,0],[0,101.47,294.97,186.23,39,0],[1,387.69,471.96,126.75,69,0],[1,117.65,474.99,126.75,69,0],[2,105.52,661.08,175.5,45,0],[0,374.54,780.43,186.23,39,0]]],[[[3,245.09,33.02,179.4,44,
0],[2,102.48,194.84,175.5,45,0],[2,381.63,311.15,175.5,45,0],[3,242.05,473.98,179.4,44,0],[0,108.56,633.78,186.23,39,0],[0,375.56,783.47,186.23,39,0]]],[[[3,241.04,54.26,179.4,44,0],[2,94.39,161.47,175.5,45,0],[2,99.45,320.25,175.5,45,0],[3,230.93,468.93,179.4,44,0],[0,380.61,630.75,186.23,39,0],[0,380.61,771.33,186.23,39,0]]]]]],sequence=[[0,0,0,1],[0,0,3,1],[0,0,0,0],[0,0,0,2],[0,0,1,0],[0,0,1,1],[0,0,3,0],[0,0,1,2],[0,0,2,1],[0,0,3,2],[0,0,2,0],[0,0,2,2],[0,0,1,0],[0,0,1,1],[0,0,3,0],[0,0,1,2],
[0,0,2,1],[0,0,3,2],[0,0,2,0],[0,0,2,2],[0,0,4,1],[0,0,4,0],[0,0,4,2],[0,0,5,0],[0,0,5,1],[0,0,5,2],[0,0,2,1],[0,0,3,2],[0,0,2,0],[0,0,2,2],[0,0,4,1],[0,0,4,0],[0,0,4,2],[0,0,5,0],[0,0,5,1],[0,0,5,2],[0,0,2,1],[0,0,3,2],[0,0,2,0],[0,0,2,2],[0,0,4,1],[0,0,4,0],[0,0,4,2],[0,0,5,0],[0,0,5,1],[0,0,5,2]];
